### ISSUE TITLE
Autocomplete: empty space is present at the top when label is not provided

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#526]
It then breaks vertical alignment. (I have added a red border to illustrate this)

![screenshot-2020-11-27--13-10](https://user-images.githubusercontent.com/2076953/100448382-73338400-30b2-11eb-8bad-0026e3b10f33.png)

**Comment by fritzSF** [comment]
Fixed in v2.4.18
