### ISSUE TITLE
Component request - multi select

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#527]
I would like to add compact view to type select in the new react based list view, but there is no react component for this yet.

![screenshot-2020-12-02--17-25](https://user-images.githubusercontent.com/2076953/100900694-61434e00-34c3-11eb-82ee-04116ddc6bb7.png)

**Comment by tomaskikutis** [comment]
I also need this for selecting target subscribers

![target subscribers](https://user-images.githubusercontent.com/2076953/144417979-6c696c3f-0b02-4153-b3cf-0b7992ea0f20.png).

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/621
https://github.com/superdesk/superdesk-ui-framework/pull/608

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/672
