### ISSUE TITLE
Dropdown: some icons can not be displayed

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#528]
When passing `filetype-icon-text` as an icon, the DOM element is rendered with a class name `icon-filetype-icon-text` and visually white space is present instead of an icon.

**Comment by fritzSF** [comment]
this not a valid classname for an icon, hence no result. Here are the avilable icons: https://ui-framework.superdesk.org/#/react/icon-font as a React component. Here as CSS classes: https://ui-framework.superdesk.org/#/components/icons

**Comment by tomaskikutis** [comment]
You are right, I was trying to use the icon names from filtering toolbar in monitoring and these icons have different names in ui-framework icons section.
