### ISSUE TITLE
Tooltips don't work inside elements that have overflow:hidden set

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#547]
![2021-04-20_16-38](https://user-images.githubusercontent.com/2076953/115415078-e327df80-a1f6-11eb-86a7-0241e63e07b8.png)

**Comment by fritzSF** [comment]
Append to body version of the tooltips is now available.

**Comment by tomaskikutis** [comment]
One of the most important practices for quality components, in my opinion, is that components should work the same and not break even if moved to another place in the application. I suggest making append to body the default and removing the option.

**Comment by fritzSF** [comment]
We had performance issues with Tooltips in the past and switched to CSS only based for that reason. So a lightweight option will continue to exist for that reason.

**Comment by tomaskikutis** [comment]
It'd be better to fix the performance issues instead. There can only be one tooltip displayed at a time, assuming they are displayed on hover, so it shouldn't be too hard to make them perform well.
