### ISSUE TITLE
Markup for react/popover is missing in the docs

### ISSUE THREAD

**Issue by petrjasek** [superdesk/superdesk-ui-framework#553]
![popover-markup](https://user-images.githubusercontent.com/179249/119456094-96c24900-bd3a-11eb-8db0-058b82aaca86.png)

**Comment by fritzSF** [comment]
This is fixed now. Props are added as well.
![popover](https://user-images.githubusercontent.com/1861461/119791122-d02ebc00-bed4-11eb-845c-88dee6ead21f.png)
