### ISSUE TITLE
Add boolean `loading` property to buttons

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#568]
It would be useful to have "loading" property for all buttons([example](https://user-images.githubusercontent.com/2076953/129196919-27213a0e-aac9-4ae7-bd59-e1fe9ee2975a.png)) for cases when actions are asynchronous.

It's possible to use a [generic loader](https://user-images.githubusercontent.com/2076953/129197272-c3855b47-6155-4841-8483-61fcdcf18f3b.png), but it would be clearer to users if the spinner was on the button they clicked.

**Comment by dzonidoo** [comment]
Fix version v.2.1.20

**Comment by tomaskikutis** [comment]
@dzonidoo can you link commits that are fixing the issue when closing issues?

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/588 @tomaskikutis

**Comment by dzonidoo** [comment]
Yep. I allready added. @tomaskikutis
