### ISSUE TITLE
Style issues in `Alert` component

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#571]
* padding is different between left/right
* predefined margin should be removed, because it is not always required. Sometimes only bottom margin is required, other times only top margin. The code will be cleaner if spacing is managed by the component rendering the alert.

![2021-09-17_15-29](https://user-images.githubusercontent.com/2076953/133791451-e422d65b-978e-4c69-8777-f99bcaafc38f.png)

**Comment by fritzSF** [comment]
The Alert component is actually not intended to be used in such cases. Rather as an stand-alone element inside forms or other mixed content, hence the default bottom margin. You will need the margin more often than not in such cases. I do agree though that it should be possible to disable the margin, if needed. We'll add the option either by adding a prop that handles the margin, or by removing it completely and enabling adding CSS classes to the component.

**Comment by pavlovicnemanja** [comment]
This improvements is done

**Comment by tomaskikutis** [comment]
@pavlovicnemanja when closing issues, can you specify the commit that fixes it and a release when it is/will be available?
