### ISSUE TITLE
Buttons do not grow in height regardless the amount of text

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#577]
I need it for "send to" pane. Here's an [example](https://user-images.githubusercontent.com/2076953/143025893-aa7f0652-ba7b-4b14-ba29-8f4ae6bbcc12.png) of text rendered outside the button. It is rendered correctly in the [current implementation](https://user-images.githubusercontent.com/2076953/143025896-8de6fd43-1575-481d-a51e-f6bb1c166918.png) of "send to" pane.

**Comment by tomaskikutis** [comment]
Hi @pavlovicnemanja. When you close an issue, can you specify the commit that resolves it or comment on reasoning for deciding not to address the issue if that's the case?

**Comment by tomaskikutis** [comment]
Sorry, I've clicked the wrong button, I didn't mean to reopen it. Well, you have a chance to close it with a proper comment now :smile:

**Comment by pavlovicnemanja** [comment]
@fritzSF what is conclusion on this ticket here?

**Comment by pavlovicnemanja** [comment]
As discussed with @fritzSF we don't want to allow buttons to grow in three lines, so in this case issue can be fixed on client-core side, but we will try to keep all labels in max two lines

**Comment by tomaskikutis** [comment]
Buttons [grow by default](https://jsfiddle.net/x3bwmc7z/) unless you are limiting it manually. Why not drop the limitation?

We never know the length of translated text and thus line count either. Why not make it default to a bigger button instead of [breaking](https://user-images.githubusercontent.com/2076953/143025893-aa7f0652-ba7b-4b14-ba29-8f4ae6bbcc12.png) the design?

**Comment by pavlovicnemanja** [comment]
@fritzSF requests, as he is a head of design I don't want to go into his decision
