### ISSUE TITLE
It doesn't work to initialize `Tabs` with n-th tab selected where n > 1

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#578]
Tabs component should accept the value indicating currently selected tab. Now, it is only possible to initialize with 1st tab selected.

I would also like the interface to be improved. It would be easier to use if there were less components and developers using the component wouldn't have to spend time thinking how to compose the components and which components are valid as children. It's easiest when interfaces are data driven and all required components are encapsulated and composed inside the main ui-framework component.

In this case, it's required to able able to render tab content in scrollable area, and selection of tabs in fixed area, so 1 component won't be enough, but 2 should work fine.

For the component that would list all tabs, I suggest using the interface posted here https://github.com/superdesk/superdesk-ui-framework/issues/576

And for the content component, the only required prop would probably be a reference ID for accessibility that would somehow link the header with content in a similar way that `label`s are linked to `input`s in HTML.

**Comment by dzonidoo** [comment]
Fix version v.2.1.20
