### ISSUE TITLE
Tag component produces invalid HTML markup when placed inside a paragraph

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#582]
`Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.`

**Comment by fritzSF** [comment]
Changed <div> to <span>

**Comment by tomaskikutis** [comment]
Thanks. Can you specify a commit which fixes it before closing the issue?

**Comment by fritzSF** [comment]
Fixed in version 2.4.18
