### ISSUE TITLE
Accessibility labels for input components

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#590]
Review all input components to ensure that they have a possibility to specify a label or pass a `aria-labelledby` prop. It'd be best if both options were available.

Passing a label isn't supported for `RadioButtonGroup`.

**Comment by fritzSF** [comment]
3.0 has that covered

**Comment by tomaskikutis** [comment]
I don't see it for `RadioButtonGroup` in `beta-3.0.0` using the latest commit 4f8d6cb

**Comment by fritzSF** [comment]
`<RadioButtonGroup options={[
    {value:'test6', label:'Button style radio'},
    {value:'test7', label:'Button style'},
    {value:'test8', label:'Button style'},
    {value:'test9', label:'Button style disabled', disabled:true},
]} value={this.state.value3} onChange={(value) => this.setState(() => ({ value3: value }))} />`

**Comment by fritzSF** [comment]
label is mandatory, it can be hidden if we want show only an icon:
`<RadioButtonGroup options={[
    {value:'test10', label:'Radio button with icon', icon:'list-view', labelHidden: true},
    {value:'test11', label:'I have an icon!', icon:'grid-view', labelHidden: true},
    {value:'test12', label:'Yeah, me too!', icon:'kanban-view', labelHidden: true},
]} value={this.state.value4} onChange={(value) => this.setState(() => ({ value4: value }))} />`

**Comment by tomaskikutis** [comment]
I was referring to a label of the radio group itself, not individual options.
![2022-03-04_18-01](https://user-images.githubusercontent.com/2076953/156807157-38069b5f-6c72-4df0-aec9-9f2f143a065d.png)

**Comment by fritzSF** [comment]
aah, OK. All clear now.

**Comment by fritzSF** [comment]
It's done in version 3.0.1-beta.0. Example:

`<RadioButtonGroup group={{groupLabel: 'My group label'}}
    options={[
    {value:'test6', label:'Button style radio'},
    {value:'test7', label:'Button style'},
    {value:'test8', label:'Button style'},
]} value={this.state.value3} onChange={(value) => this.setState(() => ({ value3: value }))} />`
