### ISSUE TITLE
Dropdown - some items are displayed outside of the viewport and can't be selected

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#598]
![not all items are displayed](https://user-images.githubusercontent.com/2076953/159466394-fb257c08-1bb0-4725-b41b-157baebce064.png)

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/696
https://github.com/superdesk/superdesk-ui-framework/pull/695
