### ISSUE TITLE
Dropdown - items sometimes remain after an option was already selected

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#599]
I suspect it is caused by component not cleaning up when being unmounted

https://user-images.githubusercontent.com/2076953/159466872-d380c194-f824-429a-b002-ce3a52785faf.mp4

**Comment by thecalcc** [comment]
https://user-images.githubusercontent.com/45574768/194345132-2d517083-6709-4aac-a404-2947fbc0ce0d.mp4

**Comment by thecalcc** [comment]
https://user-images.githubusercontent.com/45574768/194365390-a740b5c8-195a-48be-b277-ca9189006b96.mp4

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/696
https://github.com/superdesk/superdesk-ui-framework/pull/695

**Comment by tomaskikutis** [comment]
reproduces on 3.0.1-beta.14

https://user-images.githubusercontent.com/2076953/198117316-48a12e5c-f50b-4cbb-a1d9-5fc20dd94cfd.mp4

**Comment by dzonidoo** [comment]
Yes, that's a whole new issue that only show up when you delete items from the list... I'm on it...

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/710
