### ISSUE TITLE
Dropdown - displayed below modal and options can't be selected

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#600]
Can be reproduced at https://github.com/tomaskikutis/superdesk-client-core/commit/e7471d958f156a9d3e2fdd8e7f4ab29c2e915d9d

The issue doesn't reproduce if `Menu` component from ui-framework is being used - so I think the issue is with dropdown rather than with modal.

https://user-images.githubusercontent.com/2076953/159473426-5f77b716-e495-4fb4-9152-ed1c66fa3266.mp4

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/696
https://github.com/superdesk/superdesk-ui-framework/pull/695

**Comment by tomaskikutis** [comment]
Still reproduces in template editing (broadcasting module)

![image](https://user-images.githubusercontent.com/2076953/196929203-e4113368-5ec0-4273-822a-467207501322.png)

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/710
