### ISSUE TITLE
IconButton - expose more styling options

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#613]
I want to configure icon buttons to appear as in this screenshot:
![2022-05-10_16-36](https://user-images.githubusercontent.com/2076953/167654903-8f30888e-2095-42a2-b6a0-7a288f50ee87.png)

**Comment by fritzSF** [comment]
Done. Available in v.3.0.0-beta.1
Example: <IconButton style='outlineWhite' size='x-large' icon='crop' ariaValue='Edit crops' onClick={()=> false} />
You can place them in a ButtonGroup as well, like so:
`<ButtonGroup align='center' spaces='loose'>
    <IconButton style='outlineWhite' size='x-large' icon='pencil' ariaValue='Edit metadata' onClick={()=> false} />
    <IconButton style='outlineWhite' size='x-large' icon='switches' ariaValue='Edit image' onClick={()=> false} />
    <IconButton style='outlineWhite' size='x-large' icon='crop' ariaValue='Edit crops' onClick={()=> false} />
</ButtonGroup>`

**Comment by tomaskikutis** [comment]
![2022-05-25_14-06](https://user-images.githubusercontent.com/2076953/170258246-6296a2d9-1583-45e9-8497-9c6b506d6be8.png)

```
<IconButton
    icon="plus-sign"
    size="x-large"
    ariaValue={gettext('new item')}
    onClick={() => null}
/>
```

Looks like I'll need some more styling options to implement plus button. The biggest issue is that I can't choose a color. Empty space around the button looks too big as well.

**Comment by fritzSF** [comment]
You can use the default Button component:
<Tooltip text="new item" >
    <Button type="primary" icon="plus-large" text="new item" size="small" shape="round" iconOnly={true} onClick={()=> false} />
</Tooltip>

**Comment by tomaskikutis** [comment]
Thanks, that one works. Except that it doesn't support `aria-label`.

Why do we have both - `iconOnly` mode for `Button` component and separate component for icon buttons? Could one of those be removed? It seems the purpose is the same.

**Comment by fritzSF** [comment]
The 'text 'actually becomes the `aria-label` if iconOnly={true}. For now, I would keep both. IconButton is a much simpler component, intended for actions in lists, modal headers etc. Different colour options because of this were never intended.
