### ISSUE TITLE
Alert component doesn't respect margin property

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#619]
If I set it to "none" margin is still shown.

**Comment by fritzSF** [comment]
I tested this, it should work. Maybe you have and older version of the framework? Please try the latest beta - v.3.0.0-beta.1
`<Alert style='hollow' size='normal' type='success' restoreIcon='info' margin='none'>
    Sed tincidunt ipsum metus...
</Alert>`

**Comment by tomaskikutis** [comment]
My bad, I had 2 alert components, was adding a margin property on one and checking if it works on another :man_facepalming:

**Comment by fritzSF** [comment]
no worries :)
