### ISSUE TITLE
`Nav.SideBarTabs` lacks an option to display additional information like item count

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#626]
I'd like to display attachments count, but an no props to display additional information next to an icon are available.

![2022-06-10_16-55](https://user-images.githubusercontent.com/2076953/173093400-f4f7fdf0-2308-48e8-934d-c75a23d06545.png)

**Comment by fritzSF** [comment]
fix version: v.3.0.0-beta.2

**Comment by fritzSF** [comment]
Add 'badgeValue:' where needed. Example:
`<Nav.SideBarTabs
    items={[
        { icon: 'history', size: 'big', tooltip: 'History', onClick:()=> false },
        { icon: 'comments', size: 'big', tooltip: 'Inline Comments', **badgeValue: '5'**, onClick:()=> false },
        { icon: 'suggestion', size: 'big', tooltip: 'Suggestions', onClick:()=> false }]} />`
