### ISSUE TITLE
Remove `invalid` property from `Input` component

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#627]
`invalid` is a property derived from `error`. If there's an error present - `invalid` should always be true and vice versa. Otherwise it's inconvenient to use. For example, if I need to call a function to get an error message, I have to store the result in the scope so I can use it in 2 places.

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/641
