### ISSUE TITLE
fix invalid property name in `Spinner` component

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#629]
```
react_devtools_backend.js:4026 Warning: Invalid DOM property `stroke-width`. Did you mean `strokeWidth`?
    in circle (created by Spinner)
```

**Comment by fritzSF** [comment]
no, 'stroke-width' is a native SVG property.

**Comment by tomaskikutis** [comment]
The problem is that JSX is neither native HTML nor native SVG. All attributes have to be camel-cased except `aria-` and `data-` attributes. https://reactjs.org/docs/dom-elements.html

**Comment by fritzSF** [comment]
OK, no problem, I'll make the change. I feared that the SVG would not render correctly - it does dough. The funny thing is that VS Code doesn't report 'stroke-width' as an error, it usually does in such cases. Linter goes trough it as well.
Fix version: v.3.0.0-beta.2
