### ISSUE TITLE
Component request - duration input

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#630]
![2022-06-15_15-15](https://user-images.githubusercontent.com/2076953/173836163-875b342a-4670-4c46-af22-8b1d5a69f14a.png)

Can be implemented as a separate component, or simply as another input type in addition to already existing "text", "number" and "password".

What I would improve related to the input in the design, is add labels "h, m, s" so it's clear what the numbers mean, and also keep values in 2 digits - 1 minute should be represented as 01m.

It would be good to support keyboard navigation - arrows moves between hours/minutes/seconds in a similar way how it works in native date input, up/down increments/decrements values.

I imagine the end result to be similar to a combination of native date input and duration input from [audacity](https://www.audacityteam.org/)

![2022-06-15_15-31](https://user-images.githubusercontent.com/2076953/173841534-5e78bcda-dfca-4ee6-9a87-247fa9b80863.png)

**Comment by pavlovicnemanja** [comment]
@tomaskikutis what is expected output of this component? Should it be string or object?
```
{h: 00, m: 00, s: 00}
```

or

```
00.00.00
```

**Comment by tomaskikutis** [comment]
Sorry, forgot to mention this - duration in seconds `01h 0m 01s` would output to `3601` (number)

**Comment by pavlovicnemanja** [comment]
ok, tnx!

**Comment by tomaskikutis** [comment]
I've tested the component and found the following issues:
* [numbers are cut off](https://user-images.githubusercontent.com/2076953/186151611-466b8b9f-aa90-4d3e-b067-5fd9df68d1e2.png)
* focus management is broken - hitting TAB/shift+TAB should go to next/previous inputs - duration input should be treated as a single input, even if it is made of multiple parts - see native time/date inputs
* if I set value to 61 seconds, it should show as `1 min 1 sec` - instead it shows as `61 sec`. Here's a sample snippet:

```
<DurationInput
    label="'Planned duration"
    seconds={61}
    onChange={() => null}
/>
```

**Comment by tomaskikutis** [comment]
One more thing, to display a user-friendly diff view between 2 values, I need a function exported that I would pass seconds to, and the function would return a duration string in the same format as input uses e.g. `getString(3601) // '01h 00m 01s'`

**Comment by tomaskikutis** [comment]
~found a bug: component causes an infinite loop and crashes (`onChange` is being called in `componentDidUpdate`)~

**Comment by tomaskikutis** [comment]
Regarding [numbers being cut off](https://user-images.githubusercontent.com/2076953/186151611-466b8b9f-aa90-4d3e-b067-5fd9df68d1e2.png), I found that it's caused by superdesk applying paddings to all input elements. The quickest solution would be to set padding to zero inside duration input

**Comment by tomaskikutis** [comment]
* numbers are still being cut off
* `getTime`(which I renamed to `getDurationString`), should output `'01h 00m 01s'`, instead of `00:00:01`

Focus management is still not ideal since duration input is made of 3 inputs - when it should be one. Implementing it properly wouldn't be easy since it would required advanced input masks, so I guess we can live with that one.
