### ISSUE TITLE
Component request - frequency input field

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#636]
## Use case
![2022-06-17_10-42](https://user-images.githubusercontent.com/2076953/174261990-49ad10b9-7776-4ea9-aee2-ceb5f955c076.png)

## Requirements
* use `rrule` format
* should be possible to render in read-only mode
* should be possible set empty value(`null`)

## Interface
```
interface IRRule {
    freq: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY';
    interval: number;
    month: number; // [1, 12]
    monthday: number; // [-31, 31]
    weekday: number; // [0, 6] ; 0 is Monday
}


interface IProps {
    value: IRRule | null;
    onChange(value: IRRule | null): void;
    firstDayOfWeek: number; // [0, 6] ; 0 is Monday
    readOnly?: boolean;
    required?: boolean; // unless true, it should be possible to reset to empty value
}
```

## References

rrule format - https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html
reference implementations - https://icalendar.org/rrule-tool.html https://fafruch.github.io/react-rrule-generator/

**Comment by MarkLark86** [comment]
IMO the value object should be a more well defined interface containing the supported options available to the component.
For example (not complete):
```ts
interface IHourlyFrequencyValue {
    frequency: 'hourly';
}

interface IDailyFrequencyValue {
    frequency: 'daily';
    time: string;
}

interface IWeeklyFrequencyValue {
    frequency: 'weekly';
    time: string;
    days: Array<'Sunday' | 'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday'>;
}

interface IMonthlyFrequencyValue {
    frequency: 'monthly';
    time: string;
    day: number;
}

type IDateTimeFrequencyValue = IHourlyFrequencyValue | IDailyFrequencyValue | IWeeklyFrequencyValue | IMonthlyFrequencyValue;
```

This will make this component useful in areas where CRON is not used as a storage and/or traversal format.
If need be, the UI-Framework could provide a wrapper around this component to use CRON as a format.

**Comment by tomaskikutis** [comment]
cron is a more complete format, so I'd be more inclined to use it as a primary one. We could implement a subset of it if we wanted, and add more options later without having to change the interface.

I'm happy though to leave implementation details up to whoever implements it, given that there's a wrapper component provided that works with cron format.

**Comment by MarkLark86** [comment]
Will also need a `firstDayOfWeek` property to localise the list of days for the region (i.e. first day is either `Sunday` or `Monday`).
Same value as provided to `DatePicker` component (https://github.com/superdesk/superdesk-ui-framework/blob/master/app-typescript/components/DatePicker.tsx#L19)

**Comment by tomaskikutis** [comment]
@petrjasek  suggested we use rrule format instead of cron since it's more flexible. I've adjusted the issue description accordingly.

**Comment by tomaskikutis** [comment]
I've talked with Petr and we decided to stop work on this until we need the component somewhere else. For rundowns, I implemented a simple version of this that only supports weekly frequency
