### ISSUE TITLE
`DatePickerISO` component - extra spacing is present

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#639]
similar to #624

beta 3, commit a8eb76f8379f6df74b39b2bb3d0e0c885f50f0ae

![2022-06-21_13-37](https://user-images.githubusercontent.com/2076953/174790942-9db4208d-1fef-471e-ab99-b0d33f7a1ddd.png)

Usage:
```JSX
<DatePickerISO
    dateFormat={superdesk.instance.config.view.dateformat}
    value={template.air_date ?? ''}
    onChange={(val) => {
        this.props.onChange({
            ...template,
            air_date: val,
        });
    }}
/>
```

HTML generated by react component

```HTML
<div class="sd-input sd-input--inline-label"><label class="sd-input__label" for="id75" id="id75label"></label>
    <div class="sd-input__input"><span id="pr_id_13"
            class="p-calendar p-inputwrapper p-calendar-w-btn p-inputwrapper-filled"><input type="text"
                class="p-inputtext p-component" autocomplete="off" inputmode="none"><button type="button" tabindex="-1"
                class="p-button p-component p-datepicker-trigger p-button-icon-only"><span
                    class="icon-calendar p-c"></span><span class="p-button-label p-c">&nbsp;</span></button></span>
    </div>
    <div class="sd-input__message-box"></div>
</div>
```

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/642

**Comment by tomaskikutis** [comment]
Reopening due to similar issue on beta 3, commit efabe01. This time extra spacing is at the bottom.

![2022-06-30_13-11](https://user-images.githubusercontent.com/2076953/176663458-9de366b1-2c78-434d-a5fa-7bd3d41dceb2.png)

**Comment by fritzSF** [comment]
This is fixed already.

**Comment by tomaskikutis** [comment]
Could you link a commit fixing the issue when you close it? In this case, I assume it's 46595ac that fixes this?

**Comment by fritzSF** [comment]
I think it was part of a previous change, it's just now that I tested it.
