### ISSUE TITLE
Component request - large input field

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#646]
It would work if a style option was be added to the existing text field.

![2022-06-28_14-05](https://user-images.githubusercontent.com/2076953/176174388-6009db0c-b0d7-45ae-bf74-398e1c230258.png)

**Comment by fritzSF** [comment]
Added in the latest version.
`<Input label='Input label'
                                    value={''}
                                    boxedStyle={true}
                                    size='x-large'
                                    maxLength={25}
                                    type='text'
                                    placeholder='Extra large boxed input'
                                    error='This is error message'
                                    inlineLabel={true}
                                    labelHidden={true}
                                    required={this.state.required}
                                    disabled={this.state.disabled}
                                    invalid={this.state.invalid}
                                    tabindex={0}
                                    onChange={(value) => this.setState({value2: value})} />`
