### ISSUE TITLE
Support HEX colors for `Label` component

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#652]
Rundown item type options and colors will be set via a vocabulary. Vocabularies use native color inputs that output HEX colors.

![2022-07-14_11-11](https://user-images.githubusercontent.com/2076953/178947797-adf2037d-3538-4d6e-b62f-20ecce1d284b.png)

**Comment by fritzSF** [comment]
Added in the latest version:
`<Label text='Hex: #008773' hexColor='#008773'/>`
