### ISSUE TITLE
How to handle reordering of items using `TableList`?

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#654]
Could you provide an example on how would I use `TableList` and reorder users in this snippet?

```tsx
import * as React from 'react';

interface IUser {
    id: string;
    firstName: string;
    lastName: string;
}

type IProps = {};

interface IState {
    users: Array<IUser>;
}

export class UserManagement extends React.PureComponent<IProps, IState> {
    constructor(props: IProps) {
        super(props);

        this.state = {
            users: [
                {id: '1', firstName: 'John', lastName: 'Doe'},
                {id: '2', firstName: 'Jane', lastName: 'Doe'},
            ],
        };
    }

    render() {
        return (
            <div>
                <h3>users</h3>

                {
                    this.state.users.map((user) => (
                        <div key={user.id}>{user.firstName} {user.lastName}</div>
                    ))
                }
            </div>
        );
    }
}
```

**Comment by dzonidoo** [comment]
`interface IPropsArray {
    start?: React.ReactNode;
    center?: React.ReactNode;
    end?: React.ReactNode;
    action?: React.ReactNode;
}`

- This array you provide doesn't compile with interface.

`import * as React from 'react'

export class UserManagement extends React.PureComponent<IProps, IState> {
    constructor(props: IProps) {
        super(props);

        this.state = {
            users: [
                {center: 'John', end: 'Doe'},
                {center: 'Jane', end: 'Doe'},
            ],
        };
    }

    render() {
        return (
            <div>
                <h3>users</h3>

                <TableList
                 dragAndDrop
                 addItem
                 array={this.state.users}
                 />
            </div>
        );
    }
}`

**Comment by tomaskikutis** [comment]
> This array you provide doesn't compile with interface.

We will never store data in database using `{center: 'John', end: 'Doe'}` format. There has to be a way to use the component with any format - either directly or with intermediate transformed object. Can you provide a usage example within the snippet I provided without changing the `IState` interface?

**Comment by pavlovicnemanja** [comment]
@tomaskikutis 

` <TableList>
                {this.state.array.map((user) =>
                    <TableListItem
                        start={
                            <>{user.firstName} {user.lastName}</>
                        }
                        center={
                            <span>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</span>
                        }
                        end={
                            <IconLabel style='translucent' text='Label success' type='success' icon='time' />
                        }
                        action={
                            <IconButton icon='dots-vertical' size='small' ariaValue='More actions' onClick={() => false} />
                        } />
                )}
                </TableList>`

**Comment by pavlovicnemanja** [comment]
```
 <TableList>
    {this.state.array.map((user) =>
        <TableListItem
            start={
                <>{user.firstName} {user.lastName}</>
            }
            center={
                <span>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</span>
            }
            end={
                <IconLabel style='translucent' text='Label success' type='success' icon='time' />
            }
            action={
                <IconButton icon='dots-vertical' size='small' ariaValue='More actions' onClick={() => false} />
            } />
    )}
</TableList>
```

**Comment by pavlovicnemanja** [comment]
@tomaskikutis if you need some further discussion on this, just ping me

**Comment by tomaskikutis** [comment]
@pavlovicnemanja the part I'm most interested in, is how would one update the state after reordering. Can you include that in the example?

**Comment by pavlovicnemanja** [comment]
Hi @tomaskikutis I included `onDrag` prop witch should return start position and end position of item. Use case:
```
 <TableList dragAndDrop onDrag={(start, end) => console.log(start, end)}>
    {this.state.array.map((user) =>
        <TableListItem
            start={
                <>{user.firstName} {user.lastName}</>
            }
            center={
                <span>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</span>
            }
            end={
                <IconLabel style='translucent' text='Label success' type='success' icon='time' />
            }
            action={
                <IconButton icon='dots-vertical' size='small' ariaValue='More actions' onClick={() => false} />
            } />
    )}
</TableList>
```

if you need some more data, just ping me and I will add. Thanks.

**Comment by tomaskikutis** [comment]
@pavlovicnemanja I see that neither of 2 components in your example are exported and ready to be tested. Don't assign it to me until it's really ready :)

**Comment by pavlovicnemanja** [comment]
@tomaskikutis Components are now exported, you can test this

**Comment by tomaskikutis** [comment]
@pavlovicnemanja can you provide a **working** example by modifying the snippet that is in the issue description? I did take a look and don't think it would work as is.

**Comment by pavlovicnemanja** [comment]
Hi @tomaskikutis , I updated rundown playground with working example.

This is code snippet:
```
<TableList
        className='sd-margin-y--4'
        dragAndDrop
        addItem
        array={this.state.users.map((user) => {
            return {
                start: <>
                    <Label style='translucent' text='aacc' />
                    <Label style='translucent' type='primary' text='prlg' />
                </>,
                center: <>{user.firstName} {user.lastName}</>,
                onClick: () => false,
            }
        })}
        onDrag={(start, end) => 'do reordering of array here'}
        itemsDropdown={[
            { label: <Label style='translucent' type='primary' text='aacc' />, onSelect: () => 1 },
            { label: <Label style='translucent' text='prlg' />, onSelect: () => 1 },
            { label: <Label style='translucent' type='primary' text='prlg' />, onSelect: () => 1 },
        ]}
        onClick={() => false}
    />
```

![image](https://user-images.githubusercontent.com/6507688/190625315-a825c123-79a2-4240-a101-f2246498a8cc.png)

**Comment by tomaskikutis** [comment]
Thanks, it's working a little bit now.

### Issues
* `itemsDropdown` - if not provided, or is empty, errors are thrown in the console
* `itemsDropdown` - index should be provided in the callback. Otherwise it's not possible to differentiate a click between 1/2 items from a click between 5/6
* `Dropdown` component [gets covered](https://user-images.githubusercontent.com/2076953/190664900-319f15a4-456a-452d-9446-b8cc0e3ec00c.png)
* [Actions menu is glitchy](https://user-images.githubusercontent.com/2076953/190666057-557cb1e1-ab26-42ee-9ec8-2c451a729709.mp4) - if menu disappears, it should not re-appear unless triggered via tree dots button
* `array` prop is not respected - order should always be the same as in `array` prop.
* * Item at index 2 is moved to 1
*  * `onDrag` is called
* * I don't update state
* * RESULT: list is still reordered. EXPECTED: items should not be reordered and should be displayed as ordered in `array` prop.

**Comment by tomaskikutis** [comment]
A few more things that I need:
* The plus button to add an item, should be visible even if there are no items in the list yet
* There should be a `readOnly` prop, that would not allow reordering nor adding new items

**Comment by tomaskikutis** [comment]
I also need `onClick`, `onDoubleClick` handlers to trigger preview/editing. Clicking elements inside `IPropsArrayItem['acton']` should not trigger them.

**Comment by tomaskikutis** [comment]
I noticed there is no prop to pass a [border color](https://user-images.githubusercontent.com/2076953/191482057-34431fb3-ae0b-418c-bd8d-5e48084c0bb3.png), I'll need that as well. It should work with HEX colors.

**Comment by tomaskikutis** [comment]
@fritzSF I noticed [UI is moving a lot](https://user-images.githubusercontent.com/2076953/193252516-1ba04109-aec7-4498-a7f7-e5df6655a160.mp4) when user is not doing anything except moving a mouse. It'd be good to reduce it.

**Comment by fritzSF** [comment]
@tomaskikutis border color with HEX is done. Please check with @dzonidoo the right version.

**Comment by fritzSF** [comment]
> @fritzSF I noticed [UI is moving a lot](https://user-images.githubusercontent.com/2076953/193252516-1ba04109-aec7-4498-a7f7-e5df6655a160.mp4) when user is not doing anything except moving a mouse. It'd be good to reduce it.

Yes, it is quite anoing. I created a fix for this but it's not yet applied to the component. I'll handle it on Monday.

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/692

**Comment by tomaskikutis** [comment]
> `itemsDropdown` - index should be provided in the callback. Otherwise it's not possible to differentiate a click between 1/2 items from a click between 5/6 - [source](https://github.com/superdesk/superdesk-ui-framework/issues/654#issuecomment-1249470679)

Hey guys, this still doesn't work. I see that you didn't add an index as I suggested, but instead added another prop `onAddItem`. Even if we leave aside that it's not a clean approach, it doesn't work either. I get the index, but now there's no way to know which item from `itemsDropdown` was selected.

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/697
