### ISSUE TITLE
`SearchBar` - provide value when `onSubmit` is called

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#670]

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/674
I also added enter key functionality to trigger onSubmit...

**Comment by tomaskikutis** [comment]
Only close issues when work is finished - if there's an open PR, it's not finished yet

**Comment by pavlovicnemanja** [comment]
@tomaskikutis can you test and close the issue? tnx

**Comment by tomaskikutis** [comment]
I think it's an overkill for me to test every single tiny change. If you fully understand the issue, feel free to merge it and close GitHub issue without my me.

**Comment by pavlovicnemanja** [comment]
I agree, but previous agreement was not to close issue until you confirmed it.

**Comment by tomaskikutis** [comment]
Maybe it was a misunderstanding. If I don't tell in advance that I want to test a certain thing, merge it without me. I sometimes want to check some complex new components like tree select, but that's an exception, not the rule.

**Comment by pavlovicnemanja** [comment]
works for me! :)

**Comment by pavlovicnemanja** [comment]
Tested and confirmed
