### ISSUE TITLE
Duration input focus & value issue

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#676]
* input value is `01h21m02s`
* cursor is placed in the beginning of minutes field, before `2`
* `3` is typed

Actual result: minutes become `32`, cursor moves to seconds
Expected result: minutes become `31`, cursor stays in minutes

https://user-images.githubusercontent.com/2076953/189484407-cfe36627-79d1-4e54-80d9-38c51e79c505.mp4

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/678

**Comment by tomaskikutis** [comment]
Probably related: after double clicking hours minutes or seconds to select both digits - it only updates the first digit when typing and focus jumps to the next section

https://user-images.githubusercontent.com/2076953/191735106-0cf25c53-868e-471e-9b83-6342496e3df4.mp4

**Comment by dzonidoo** [comment]
https://www.loom.com/share/c238fddd10cd4dbebd6a316f67698619

**Comment by tomaskikutis** [comment]
reproduces here https://github.com/tomaskikutis/superdesk-ui-framework/tree/duration-bug

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/711
