### ISSUE TITLE
`Layout.Panel` - controlling the size doesn't work

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#677]
I tried setting `size="full"` and `size="auto"` but neither make the panel take 100% of width.

```jsx
<Layout.Panel side="right" open={true} size="full" background={this.props.background ?? 'light'}>
...
</Layout.Panel>
```

Can be tested at https://sd-broadcasting.test.superdesk.org/  (rundown 002)

client: 9152c67af (latest at broadcasting branch)
ui-framework: 09b6208 (latest at beta 3 branch)

![image](https://user-images.githubusercontent.com/2076953/189937906-bdf84f35-66b1-4538-85b4-3b45b4023d9a.png)

**Comment by fritzSF** [comment]
It's a CSS isue on the parent container. I'm fixing it in the next commit.
