### ISSUE TITLE
`TimePicker` - validation errors do not appear

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#687]
https://user-images.githubusercontent.com/2076953/191959789-94ded3f6-a872-4b25-b4b8-6ffecfaa6347.mp4

related to https://github.com/superdesk/superdesk-ui-framework/issues/660

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/691
