### ISSUE TITLE
`Dropdown` doesn't position correctly in certain cases

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#690]
Reproduces on the broadcasting instance

https://user-images.githubusercontent.com/2076953/192500984-8c965203-af50-43bc-85a9-d007e1093d4f.mp4

**Comment by tomaskikutis** [comment]
Still reproduces at c918271


https://user-images.githubusercontent.com/2076953/196232284-c7952dd6-664c-4c57-bbd8-7c270c57a85d.mp4

**Comment by dzonidoo** [comment]
its done... just need to merge

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/696
