### ISSUE TITLE
`Layout.LayoutContainer` is not rendered, but still takes space

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#693]
In order to hide rundown list when rundown item is being previewed or edited, I don't render [Layout.LayoutContainer](https://github.com/superdesk/superdesk-client-core/blob/broadcasting/scripts/extensions/broadcasting/src/page.tsx#L77). Whitespace is still being shown in its place.

https://user-images.githubusercontent.com/2076953/193625652-8025223e-9dbd-4af3-963a-d47582a63a69.mp4

**Comment by fritzSF** [comment]
@tomaskikutis, please add the class `sd-content-wrapper--editor-full` to this element: `<section class="sd-content sd-content-wrapper">` with the same condition you stop rendering Layout.LayoutContainer.

**Comment by fritzSF** [comment]
It's merged but no release has been created with this. I'll let you know once it's created

**Comment by tomaskikutis** [comment]
I've tested and released it. All is working well. Code quality wise it'd be better to avoid loose class names and add a dedicated component, like `LayoutGroup` that would set classes as needed.
