### ISSUE TITLE
Allow ContentDivider's margin to be adjusted

### ISSUE THREAD

**Issue by thecalcc** [superdesk/superdesk-ui-framework#702]
When a ContentDivider element is present between a Spacer it makes it so it has unnecessary space around the other elements.
![image](https://user-images.githubusercontent.com/45574768/197544640-dcc4789c-41b6-4030-820b-cd6d6f5bbc23.png)

**Comment by fritzSF** [comment]
Margin prop added. `margin?: 'x-small' | 'small' |'medium' | 'large' | 'none';` // Defaults to 'medium' (same value as currently)
fix version: v3.0.0-rc8
