### ISSUE TITLE
When `Label` is used inside a button, a pointer style cursor is not shown

### ISSUE THREAD

**Issue by tomaskikutis** [superdesk/superdesk-ui-framework#718]
It has `cursor: default` CSS style. Removing it would solve the issue - the cursor style would then be inherited from button and would resolve to `pointer`

[image](https://user-images.githubusercontent.com/2076953/203305639-28e9b712-c7ae-47c7-8c50-b837095ba099.png)

**Comment by dzonidoo** [comment]
https://github.com/superdesk/superdesk-ui-framework/pull/724
